import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'vi',
        'hi',
        'ja',
        'ar',
        'th',
        'es',
        'ko',
        'zh_Hans',
        'fr',
        'tr',
        'ru',
        'de',
        'pt',
        'it'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? viText = '',
    String? hiText = '',
    String? jaText = '',
    String? arText = '',
    String? thText = '',
    String? esText = '',
    String? koText = '',
    String? zh_HansText = '',
    String? frText = '',
    String? trText = '',
    String? ruText = '',
    String? deText = '',
    String? ptText = '',
    String? itText = '',
  }) =>
      [
        enText,
        viText,
        hiText,
        jaText,
        arText,
        thText,
        esText,
        koText,
        zh_HansText,
        frText,
        trText,
        ruText,
        deText,
        ptText,
        itText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // SplashScreen
  {
    '3pndpmm6': {
      'en': 'Make a commitment to managing your diabetes ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'अपने मधुमेह को नियंत्रित करने के लिए प्रतिबद्ध रहें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Hãy cam kết kiểm soát bệnh tiểu đường của bạn.',
      'zh_Hans': '',
    },
    'zjofth0v': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // onBoarding
  {
    'c66ff00y': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // SplashScreenCopy
  {
    '8kgornvz': {
      'en': 'Make a commitment to managing your diabetes ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'अपने मधुमेह को नियंत्रित करने के लिए प्रतिबद्ध रहें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Hãy cam kết kiểm soát bệnh tiểu đường của bạn.',
      'zh_Hans': '',
    },
    'iewjyv96': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // PrimaryGoalPage
  {
    '0clwk2zl': {
      'en': '0',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '0',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '0',
      'zh_Hans': '',
    },
    '5ftogwhi': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // LogIn
  {
    'feux0xjh': {
      'en': 'Join glucoPal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'ग्लूकोपाल से जुड़ें',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Hãy tham gia GlucoPal',
      'zh_Hans': '',
    },
    '3ruqx7uw': {
      'en': 'Full Name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'पूरा नाम',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Họ và tên đầy đủ',
      'zh_Hans': '',
    },
    '19z0lruv': {
      'en': 'Enter your full name',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'अपना पूरा नाम भरें',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Nhập đầy đủ họ của bạn',
      'zh_Hans': '',
    },
    '8ldmiv4k': {
      'en': 'Sign up with Google',
      'ar': 'سجل باستخدام جوجل',
      'de': 'Mit Google anmelden',
      'es': 'Regístrate con Google',
      'fr': 'Inscrivez-vous avec Google',
      'hi': 'Google के साथ साइन अप करें',
      'it': 'Registrati con Google',
      'ja': 'Googleでサインアップ',
      'ko': 'Google 계정으로 가입하세요',
      'pt': 'Faça login com o Google',
      'ru': 'Зарегистрируйтесь через Google',
      'th': 'ลงทะเบียนกับ Google',
      'tr': 'Google ile kaydolun',
      'vi': 'Đăng ký bằng Google',
      'zh_Hans': '使用 Google 账号注册',
    },
    '7bdr8u78': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'k7xjshgr': {
      'en': 'Sign up with Apple',
      'ar': 'سجل باستخدام Apple',
      'de': 'Bei Apple anmelden',
      'es': 'Regístrate con Apple.',
      'fr': 'Inscrivez-vous avec Apple',
      'hi': 'Apple के साथ साइन अप करें',
      'it': 'Registrati con Apple',
      'ja': 'Appleに登録',
      'ko': 'Apple에 가입하세요',
      'pt': 'Cadastre-se na Apple',
      'ru': 'Зарегистрируйтесь в Apple',
      'th': 'ลงทะเบียนกับ Apple',
      'tr': 'Apple\'a kaydolun',
      'vi': 'Đăng ký bằng Apple',
      'zh_Hans': '使用 Apple 注册',
    },
    'm4n964s2': {
      'en': 'Enter your name is required',
      'ar': 'إدخال اسمك مطلوب',
      'de': 'Die Eingabe Ihres Namens ist erforderlich.',
      'es': 'Introduce tu nombre es obligatorio',
      'fr': 'Votre nom est obligatoire.',
      'hi': 'अपना नाम दर्ज करना आवश्यक है',
      'it': 'Inserisci il tuo nome è obbligatorio',
      'ja': '名前の入力は必須です',
      'ko': '이름을 입력하세요. (필수 입력 사항입니다.)',
      'pt': 'É obrigatório inserir seu nome.',
      'ru': 'Введите ваше имя (обязательно).',
      'th': 'กรุณาป้อนชื่อของคุณ (จำเป็น)',
      'tr': 'Adınızı girmeniz zorunludur.',
      'vi': 'Nhập tên của bạn (bắt buộc)',
      'zh_Hans': '请输入您的姓名（必填）',
    },
    '2c15hif4': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Vui lòng chọn một tùy chọn từ menu thả xuống.',
      'zh_Hans': '',
    },
    'opbonq0r': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // HomePage
  {
    'vwkf43km': {
      'en': 'WELCOME BACK,',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'o5a70w18': {
      'en': 'CURRENT GLUCOSE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'q3z7sulw': {
      'en': '108',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'fv62ebg9': {
      'en': 'MG/DL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'hiozrqxf': {
      'en': 'STABLE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'hw9qxa5r': {
      'en': 'Daily Health\nScore',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'c99cejl4': {
      'en': 'Your metabolic health\nis ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '4qanyb6h': {
      'en': '94% ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'q8ukc0do': {
      'en': 'better than\nlast week.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'kib2hvim': {
      'en': 'EXCELLENT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'tf576qwt': {
      'en': 'BLOOD \nPRESSURE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'w0osj4ul': {
      'en': '118/78 ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'dnfz1wf2': {
      'en': 'mmHg',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'mbabm4vu': {
      'en': 'HEART RATE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'klkpnkl5': {
      'en': '64',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'n552cl8y': {
      'en': ' bpm',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'fqw73r1j': {
      'en': 'WEIGHT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ryova8xm': {
      'en': '76.4 ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'w3n0fn44': {
      'en': 'kg',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'u5vji6um': {
      'en': 'STEPS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ep04jq6y': {
      'en': '8.4K ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '1f58lok4': {
      'en': 'Sync',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '4tdi70vy': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // FoodPage
  {
    'ulvao65q': {
      'en': 'GlucoPal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'w6u609gk': {
      'en': 'Daily Summary',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'akx2wbcx': {
      'en': 'CALORIES CONSUMED',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '8bdrhw54': {
      'en': '1,350',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'n4g2sab3': {
      'en': '/ 1800 kcal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0elzvvxf': {
      'en': '50%',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ncl5re2r': {
      'en': 'CARBS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'a704tftd': {
      'en': '145g',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'm8om69bw': {
      'en': '-5%',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '3bgk5xp8': {
      'en': 'SUGAR',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'd80tdbxr': {
      'en': '22g',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'g791gig3': {
      'en': '+2%',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zgh12a2s': {
      'en': 'Meals Today',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xtz4v87c': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Trang chủ',
      'zh_Hans': '',
    },
  },
  // RecentMeal
  {
    'o09zgdhn': {
      'en': 'Recent Meals',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wo3ebz5e': {
      'en': 'TEXT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'yr1vs02g': {
      'en': 'CAMERA',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wud8qvdm': {
      'en': 'RECENT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'aqan8tnx': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // TextMeal
  {
    '0l1zb1dz': {
      'en': 'Log Meal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '27lhtcfa': {
      'en': 'Manual Entry',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'lwx2pmbu': {
      'en': 'Add food by description for precise\ntracking.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'qbw6zzul': {
      'en': 'What did you eat? Describe your \nmeal...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'tfm3bwi8': {
      'en': 'Analyze',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'w9zp06te': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // AnalyzeFood
  {
    '50iwpym5': {
      'en': 'GlucoPal AI Vision v2.4',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rcfk4vfx': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // DetailsAnlyzeScreen
  {
    'zdonybrl': {
      'en': 'IDENTIFIED INGREDIENTS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'q7gymnt6': {
      'en': 'Diabetic Safety\nScore',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'tn8137o0': {
      'en': ' ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'it01pjfi': {
      'en': 'PROTEIN',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '11brqanx': {
      'en': 'CARBS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xhv4jk4a': {
      'en': 'SUGAR',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wzp0veew': {
      'en': '1.0x',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'nun5jt2o': {
      'en': 'MEAL TIME',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '5rh58q2v': {
      'en': 'AI Nutrition Analysis',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '94896908': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // AnalyzedFailed
  {
    'ispznxjc': {
      'en': 'Analysis Failed',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wkx5uin2': {
      'en':
          'We couldn\'t understand that description.\nPlease try again with different words or\ntake a photo for a more accurate scan.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '4eg6d3t7': {
      'en': 'Try Again',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'azlkuuq7': {
      'en': 'Go to Dashboard',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'p0qeb6px': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // DetailsAnlyzeEdit
  {
    'n0to6mk8': {
      'en': 'AI Nutrition Analysis',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'my4t5u6i': {
      'en': 'IDENTIFIED INGREDIENTS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zb5wfgp3': {
      'en': 'EDIT INGREDIENTS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '46iqr5lh': {
      'en': 'Diabetic Safety\nScore',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bvwl3ak5': {
      'en': ' ',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '7ihe9nnt': {
      'en': 'PROTEIN',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xholegd2': {
      'en': 'CARBS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'q8lwstp4': {
      'en': 'SUGAR',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'gkylkdqd': {
      'en': '1.0x',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pdinnsaz': {
      'en': 'MEAL TIME',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '8mjht9m7': {
      'en': 'Update Meal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'mtwx75x2': {
      'en': 'Discard & Cancel',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'x6pw533q': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // GlucoseHome
  {
    'ofqs3ha4': {
      'en': 'Glucose Log',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0yjppymx': {
      'en': 'CURRENT READING',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'kro3coph': {
      'en': 'mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'gxymydw4': {
      'en': 'Normal Range',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wewpfmsr': {
      'en': 'Meal Timing',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '45xwb6bb': {
      'en': 'Notes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'sd5jymnj': {
      'en': 'Add details about your meal or feelings...',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'gw3dobli': {
      'en': 'ANALYSIS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wmxidexs': {
      'en':
          'Your levels are within the target range for a\npre-meal reading. Stable trend compared to\nyesterday.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'y3fzreyw': {
      'en': 'Save Log',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'v0mkce6h': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // GlucoseDetails
  {
    '9d3tbau9': {
      'en': 'Log Success',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'l6352j7o': {
      'en': 'Glucose Log Saved',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    's6mjhowl': {
      'en': 'Great job keeping track of your health today!',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '4uq0r12l': {
      'en': 'QUICK ANALYSIS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'qm302p6u': {
      'en': 'IN RANGE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'z2ghuxd0': {
      'en': '110',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'mr4qvc04': {
      'en': 'mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '98pc1arx': {
      'en': 'LOGGED AT 6:45 PM',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ygj29gra': {
      'en': '7-day Average',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xqf3k7tx': {
      'en': '105 mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bd7m792d': {
      'en':
          'You\'re 5% above your average, but still well within your target range of 80-130\nmg/dL.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'vg70so19': {
      'en': 'Recent Trends',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'k40udh4p': {
      'en': 'DAILY DETAILS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'iwigsr5s': {
      'en': '10:30 AM',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'yvadwl0u': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'j1ih7dzv': {
      'en': ' mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '5g6stu89': {
      'en': '10:30 AM',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    's2ag22yo': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'v33rzfh2': {
      'en': ' mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wd4t2uqg': {
      'en': '10:30 AM',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'cilkf9qv': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'en0o7flf': {
      'en': ' mg/dL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wecc40d1': {
      'en': 'Back to Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    't5ggysrj': {
      'en': 'Log Another Entry',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0ppbkkna': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // GLHistory
  {
    'xpcmfcfg': {
      'en': 'Glucose History',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'uvync160': {
      'en': 'TODAY',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ekfzklvl': {
      'en': 'Oct 24, 2023',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '1wyexk6n': {
      'en': 'Daily Summary',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'jr0r9j15': {
      'en': 'Average',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xmzfdapq': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pcbhwfbq': {
      'en': 'MG/DL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'qo6qo9cp': {
      'en': 'Average',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'f1ay0c1n': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wyacu93h': {
      'en': 'MG/DL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0k0y62h6': {
      'en': 'Average',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zfm0w6dm': {
      'en': '112',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'e9j5uw4r': {
      'en': 'MG/DL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '3ccb1cdz': {
      'en': 'Daily Logs',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'x4g39uk4': {
      'en': '8 Entries',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'dabqr9i0': {
      'en': '8:30 PM',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'g50h3s6b': {
      'en': '124',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bvgvk7js': {
      'en': 'MG/DL',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '4rew7snh': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // LogHome
  {
    'ehtgctol': {
      'en': 'Log Activity',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'i0p5rgcz': {
      'en': 'Record your movement to track glucose\nimpact.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bo7crvn0': {
      'en': 'Sync Health Data',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '843u22od': {
      'en': 'Automatically import activities from Apple\nHealth & Google Fit.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'gbxduhaw': {
      'en': 'Sync Now',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bdoepw8k': {
      'en': 'Manual Log',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'r7xss7dv': {
      'en': 'Can\'t find your activity?',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'r0305nnu': {
      'en': 'Add Custom',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wi8yk6lg': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // caloriesBurn
  {
    'eqf3cvft': {
      'en': 'Log Activity',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'q3g2vjrk': {
      'en': 'Walking',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'h8h7ujaw': {
      'en': 'Low intensity, steady state',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'knafkqv3': {
      'en': 'Duration',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bdfd9iyb': {
      'en': 'Minutes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ois7js4v': {
      'en': 'Intensity',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '2hbflxt3': {
      'en': 'Time of Activity',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'f0i3g0ss': {
      'en': 'Estimated burn will appear here after\ncalculation',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '1rowrp3y': {
      'en': 'CALCULATE BURN',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'bhjm3nnw': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // Heart
  {
    'hkrh0w85': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // nav
  {
    '9qm68qe1': {
      'en': 'HOME',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'घर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'TRANG CHỦ',
      'zh_Hans': '',
    },
    '7ntpvgft': {
      'en': 'FOOD',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'खाना',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'ĐỒ ĂN',
      'zh_Hans': '',
    },
    'qju0u15a': {
      'en': 'HEALTH',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'स्वास्थ्य',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'SỨC KHỎE',
      'zh_Hans': '',
    },
    '7ek940ta': {
      'en': 'REPORTS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'रिपोर्टों',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'BÁO CÁO',
      'zh_Hans': '',
    },
    'aat8aa9m': {
      'en': 'PROFILE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'प्रोफ़ाइल',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'HỒ SƠ',
      'zh_Hans': '',
    },
  },
  // Logout
  {
    'lz5qihxi': {
      'en': 'Sign out',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'साइन आउट',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Đăng xuất',
      'zh_Hans': '',
    },
    'ekoxnjfw': {
      'en':
          'Staying signed in will help you track your health regularly. Are you want to sign out?',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'लॉग इन रहने से आपको नियमित रूप से अपने स्वास्थ्य पर नज़र रखने में मदद मिलेगी। क्या आप लॉग आउट करना चाहते हैं?',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Việc duy trì trạng thái đăng nhập sẽ giúp bạn theo dõi sức khỏe thường xuyên. Bạn có muốn đăng xuất không?',
      'zh_Hans': '',
    },
    'xse1zzof': {
      'en': 'Cancel',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'रद्द करना',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Hủy bỏ',
      'zh_Hans': '',
    },
    'qzjapw40': {
      'en': 'Yes',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'हाँ',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Đúng',
      'zh_Hans': '',
    },
  },
  // PrimaryGoal2
  {
    '67t46fe0': {
      'en':
          'Age and gender both affect your cardiovascular health. this information help us tailor your results to you.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'उम्र और लिंग दोनों ही आपके हृदय स्वास्थ्य को प्रभावित करते हैं। यह जानकारी हमें आपके लिए उपयुक्त परिणाम तैयार करने में मदद करती है।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Tuổi tác và giới tính đều ảnh hưởng đến sức khỏe tim mạch của bạn. Thông tin này giúp chúng tôi điều chỉnh kết quả phù hợp với từng cá nhân.',
      'zh_Hans': '',
    },
  },
  // PrimaryGoal3
  {
    'me9cvzpt': {
      'en':
          'Age and gender both affect your cardiovascular health. this information help us tailor your results to you.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'उम्र और लिंग दोनों ही आपके हृदय स्वास्थ्य को प्रभावित करते हैं। यह जानकारी हमें आपके लिए उपयुक्त परिणाम तैयार करने में मदद करती है।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Tuổi tác và giới tính đều ảnh hưởng đến sức khỏe tim mạch của bạn. Thông tin này giúp chúng tôi điều chỉnh kết quả phù hợp với từng cá nhân.',
      'zh_Hans': '',
    },
  },
  // PrimaryGoal4
  {
    'z2iuf1pn': {
      'en': 'SAFE CHOICE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'सुरक्षित विकल्प',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'LỰA CHỌN AN TOÀN',
      'zh_Hans': '',
    },
    '1370wpkf': {
      'en': 'HIGH FIBER',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'उच्च फाइबर',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'GIÀU CHẤT XƠ',
      'zh_Hans': '',
    },
    '7vkkinwl': {
      'en': 'LOW GLYCEMIC',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'कम ग्लाइसेमिक',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'CHỈ SỐ ĐƯỜNG HUYẾT THẤP',
      'zh_Hans': '',
    },
    '7y9gm5i2': {
      'en':
          'Age and gender both affect your cardiovascular health. this information help us tailor your results to you.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'उम्र और लिंग दोनों ही आपके हृदय स्वास्थ्य को प्रभावित करते हैं। यह जानकारी हमें आपके लिए उपयुक्त परिणाम तैयार करने में मदद करती है।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Tuổi tác và giới tính đều ảnh hưởng đến sức khỏe tim mạch của bạn. Thông tin này giúp chúng tôi điều chỉnh kết quả phù hợp với từng cá nhân.',
      'zh_Hans': '',
    },
  },
  // FoodComp
  {
    's2dn6vrg': {
      'en': 'HIGH SPIKE',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'i8h3tbch': {
      'en': 'Health Score',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'vs9istvi': {
      'en': 'CARBS',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zj72i8z7': {
      'en': 'PROT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'r0tyf7j4': {
      'en': 'FAT',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rxgfz5e8': {
      'en': 'SUGAR',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xfqu2k6q': {
      'en': 'View Macros',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '2ff5ptge': {
      'en': 'Analyze Spike',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // MealTime
  {
    'ghm9n8yw': {
      'en': 'Select Meal Time',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'tm0hvk03': {
      'en': 'When did you have this meal?',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'al36yxb4': {
      'en': 'Today',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'qju2j0dn': {
      'en': 'Yesterday',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'nsi4z64m': {
      'en': 'Confirm Time',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // addIngredient
  {
    'bkncocip': {
      'en': 'AI Nutrition Analysis',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ne5wna1s': {
      'en': 'INGREDIENT NAME',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '9s25s4bc': {
      'en': 'e.g. Greek Yogurt, Chicken Breast',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'vz6u5mra': {
      'en': 'Add to List',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // EditIngredient
  {
    'yrmxa5e3': {
      'en': 'Edit Ingredient',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '70mokb9k': {
      'en': 'DISH NAME',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rh8xbd0s': {
      'en': 'TextField',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'avugqgqq': {
      'en': 'Ingredients List',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'te799wrx': {
      'en': 'Add Ingredient',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wm9d53sq': {
      'en': 'Update Analysis',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'avul3h7k': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'h03qgapy': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '38tjlt8g': {
      'en': 'Allow camera to snap food and see nutrition info.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': 'कैमरे को भोजन की तस्वीर लेने दें और पोषण संबंधी जानकारी देखें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Cho phép camera chụp ảnh thức ăn và xem thông tin dinh dưỡng.',
      'zh_Hans': '',
    },
    'twufhawl': {
      'en': 'This app does not record audio. Microphone access is not used.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'यह ऐप ऑडियो रिकॉर्ड नहीं करता है। इसमें माइक्रोफ़ोन का उपयोग नहीं किया जाता है।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Ứng dụng này không ghi âm. Quyền truy cập micro không được sử dụng.',
      'zh_Hans': '',
    },
    '0rt1slcm': {
      'en': 'Allow gallery to snap or pick food and see nutrition info.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'गैलरी को भोजन की तस्वीर खींचने या चुनने और पोषण संबंधी जानकारी देखने की अनुमति दें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Cho phép chụp ảnh hoặc chọn thực phẩm và xem thông tin dinh dưỡng.',
      'zh_Hans': '',
    },
    '3w50pj4p': {
      'en':
          'Track your active calories burned during physical activities to monitor your energy expenditure.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपनी ऊर्जा खपत पर नज़र रखने के लिए शारीरिक गतिविधियों के दौरान खर्च की गई सक्रिय कैलोरी को ट्रैक करें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi lượng calo tiêu hao trong các hoạt động thể chất để giám sát mức tiêu hao năng lượng của bạn.',
      'zh_Hans': '',
    },
    'e8adu1yv': {
      'en':
          'Monitor your blood glucose levels to help manage your diabetes and maintain healthy blood sugar.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपने मधुमेह को नियंत्रित करने और स्वस्थ रक्त शर्करा स्तर बनाए रखने के लिए अपने रक्त शर्करा के स्तर की निगरानी करें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi lượng đường trong máu để giúp kiểm soát bệnh tiểu đường và duy trì lượng đường trong máu ở mức khỏe mạnh.',
      'zh_Hans': '',
    },
    'crjexk5s': {
      'en':
          'Monitor your systolic blood pressure to track your cardiovascular health.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपने हृदय संबंधी स्वास्थ्य पर नज़र रखने के लिए अपने सिस्टोलिक रक्तचाप की निगरानी करें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': 'Theo dõi huyết áp tâm thu để đánh giá sức khỏe tim mạch của bạn.',
      'zh_Hans': '',
    },
    'b1n14aww': {
      'en':
          'Track your body temperature to monitor your overall health and detect potential fever.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपने शरीर के तापमान पर नज़र रखें ताकि आप अपने समग्र स्वास्थ्य की निगरानी कर सकें और संभावित बुखार का पता लगा सकें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi nhiệt độ cơ thể để giám sát sức khỏe tổng thể và phát hiện sớm nguy cơ sốt.',
      'zh_Hans': '',
    },
    'saw56dhy': {
      'en':
          'Monitor your heart rate to track your cardiovascular fitness and detect irregular patterns.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपनी हृदय गति पर नज़र रखें ताकि आप अपनी हृदय संबंधी फिटनेस का पता लगा सकें और अनियमित पैटर्न का पता लगा सकें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi nhịp tim để đánh giá sức khỏe tim mạch và phát hiện các bất thường.',
      'zh_Hans': '',
    },
    'kqold3ci': {
      'en':
          'Track your resting calories burned to understand your basal metabolic rate.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपनी बेसल मेटाबोलिक दर को समझने के लिए, आराम करते समय खर्च होने वाली कैलोरी की मात्रा पर नज़र रखें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi lượng calo tiêu hao khi nghỉ ngơi để hiểu rõ tỷ lệ trao đổi chất cơ bản của bạn.',
      'zh_Hans': '',
    },
    '1269zxl3': {
      'en':
          'Count your daily steps to track your physical activity and maintain an active lifestyle.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपनी शारीरिक गतिविधि पर नज़र रखने और सक्रिय जीवनशैली बनाए रखने के लिए प्रतिदिन अपने कदमों की गिनती करें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Hãy đếm số bước đi hàng ngày để theo dõi hoạt động thể chất và duy trì lối sống năng động.',
      'zh_Hans': '',
    },
    '4q8597ox': {
      'en':
          'Track the distance you walk and run to monitor your physical activity levels.',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi':
          'अपनी शारीरिक गतिविधि के स्तर पर नज़र रखने के लिए, आप जितनी दूरी पैदल चलते हैं और दौड़ते हैं, उसे रिकॉर्ड करें।',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi':
          'Theo dõi quãng đường bạn đi bộ và chạy để giám sát mức độ hoạt động thể chất của mình.',
      'zh_Hans': '',
    },
    'dc2tm5ne': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'np5s895w': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '3l12ehq6': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xdq9g4a6': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pqgfdd1x': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'nwlf4ult': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'suiqtgkf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'k1q0kbyu': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rb2m8i6s': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'vn8bajzo': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wigkemvf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'fv40eog4': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pp3uvxhn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '5dkdeymq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'hbrgqfvp': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'xulfqhov': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'eidjprm8': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '3ltokdp5': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '17yqqvuv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'z20wtimn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ds43p4qh': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'refcgzol': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '9uw68nd2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'rm06n84v': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '1iusovt9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
